config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users
  root "memos#index"
  get "/settings", to: "settings#index"
  get "/search/(:id)", to: "memos#search"
  resources :memos do
    collection do
      get "search"
      get "(:id)", action: :index
    end
  end
  get "/memos/search/(:id)", to: "memos#search"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
  scope :filter_by_tag, ->(tagid) { joins(:tags).where(tags: { id: tagid }) }
  scope :filter_by_date, lambda { |date| where("strftime('%m/%d/%Y',datetime(created_at,'localtime')) = ?", date) }
  belongs_to :user
  has_and_belongs_to_many :tags
  def get_tags
    @tag_names = ""
    tag_ids.each do |tag|
      @tag_names << Tag.find(tag).name << ","
    end
  @tag_names.chop
  end
end

app/models/memos_tag.rb
class MemosTag < ApplicationRecord
  belongs_to :memo
  belongs_to :tag
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :memos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :registerable
  has_many :memos, -> { order(created_at: :desc) }

  def email_required?
    false
  end

  ## for ActiveRecord 5.1+
  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/memos_controller.rb
require "base64"

 class MemosController < ApplicationController
  def index
    @tid = params[:tid]
    @date = params[:date]
    if @tid
      @memos = Memo.filter_by_tag @tid
    elsif @date
      @memos = Memo.filter_by_date(@date).order("created_at")
    else
      @memos = current_user.memos.load_async
    end
  end

  def search
    if params[:id]
@memos = Memo.find_by_sql("SELECT * from memos INNER JOIN memos_tags on memos.id = memos_tags.memo_id where tag_id = " + params[:id])
    else
      @memos = Memo.all
    end
  end

  def show
    @memo = Memo.find(params[:id])
  end

  def new
    @memo = Memo.new
  end

  def create
    @params = memo_params
    if @params[:tagName] && !@params[:tagName].blank?
      @tagName = @params[:tagName]
      @params.delete(:tagName)
    end
    m = nil
    if @params[:body] && !@params[:body].blank?
      m = /#(.*?) /.match(@params[:body])
      if !m.nil? && m.size > 1
        body = @params[:body]
        for a in 1..m.size-1 do
          body.gsub!("##{m[a]} ", "")
        end
        @params[:body] = body.strip
      end
    end
    @memo = current_user.memos.build(@params)

    if @memo.attachment
      attachmentFile = params[:memo][:attachment]
      enc = Base64.encode64(attachmentFile.read)
      @memo.attachment = enc
    end

    if @memo.save
      if !m.nil? && m.size > 1
        for a in 1..m.size-1 do
          next if m[a].blank?
          tagRecord = Tag.where(name: m[a])
          if tagRecord.one?
            @memo.tags << tagRecord
          else
            @memo.tags.create!({ name: m[a] })
          end
        end
      end
      if @tagName
        @tagName.split(",").each do |tag|
          tagRecord = Tag.where(name: @tagName)
          if tagRecord.one?
            @memo.tags << tagRecord
          else
            @memo.tags.create!({ name: tag })
          end
        end
      end

      redirect_to action: "index"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy

    redirect_to root_path, status: :see_other
  end

  def update
      @memo = Memo.find params[:id]
      @memo.update memo_params
      respond_to do |format|
        format.js { render partial: "layouts/memo", object: @memo }
        format.html { render partial: "layouts/memo", object: @memo }
      end
  end

  private

  def memo_params
    params.require(:memo).permit(:title, :body, :attachment, :tagName)
  end
 end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
    def index
        @settings = Setting.all
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ]

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy!

    respond_to do |format|
      format.html { redirect_to tags_path, status: :see_other, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.expect(tag: [ :name ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tag_cloud
    @tags = Tag.all
    render partial: "layouts/tags/listing", locals: { tags:  @tags }
  end
end

app/helpers/memos_helper.rb
module MemosHelper
  require "redcarpet"
  require "rouge"
  require "rouge/plugins/redcarpet"
  require "markdown_checkboxes"

  class CustomRender < Redcarpet::Render::HTML
    include Rouge::Plugins::Redcarpet
  end

  @@markdown = CheckboxMarkdown.new(CustomRender, fenced_code_blocks: true)

  def renderMarkdown(text)
    @@markdown.render(text)
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_dialog.html.erb
<dialog id="turbo-confirm" class="w-96 rounded-lg relative top-[-4rem] px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:p-6" style="background: var(--ctp-frappe-surface1);color: var(--ctp-frappe-text)">
  <form method="dialog">
    <div class="sm:flex sm:items-start">
      <div class="mx-auto flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-red-100 sm:mx-0 sm:h-10 sm:w-10">
        <svg class="size-6 text-red-600" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"></path>
        </svg>
      </div>
      <div class="mt-3 text-center sm:ml-4 sm:mt-0 sm:text-left">
        <div class="mt-2">
          <p class="text-sm text-gray-500">Are you sure you want to delete this memo?</p>
        </div>
      </div>
    </div>
    <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
      <button value="confirm" class="button is-danger">Confirm</button>
      <button value="cancel" class="button is-warning">Cancel</button>
    </div>
  </form>
</dialog>

app/views/layouts/_header.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="/">
      <i class="fa-regular fa-note-sticky icon fa-2x"></i>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">      
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
        <% if user_signed_in? %>
        <%= link_to "Settings", settings_path %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete,
  form: {data: {turbo_confirm: 'Are you sure?'}} %>
          <% else %>
          <%= link_to "Sign Up", new_user_registration_path %>
          <%= link_to "Sign In", new_user_session_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_memo.html.erb
<% @guid = (0...50).map { ("a".."z").to_a[rand(26)] }.join %>
<div id="memo" hx-include="#<%= @guid %>" hx-target="this">
  <div class="card">
    <div class="card-content viewMemo">
      <div class="content">
        <%= raw renderMarkdown(memo.body) %>
        <% if memo.attachment != nil && memo.attachment != 0 %>
          <div id="modal1" class="modal">
            <div class="modal-background"></div>
            <div class="modal-content">
              <p class="image is-1by1">
                <img
                  src="data:image/png;base64,<%= memo.attachment %>"
                  style="width:auto;height:auto"
                />
              </p>
            </div>
            <button class="modal-close is-large" aria-label="close"/>
          </div>
          <img
            src="data:image/png;base64,<%= memo.attachment %>"
            style="width:200px"
            onclick="openModal();"
          />
        <% end %>
        <% memo.tag_ids.each do |tagid|
          tag = Tag.find(tagid) %>
          <%= link_to "#" + tag.name, root_path(tid: tagid) %>
        <% end %>
      </div>
    </div>
    <div class="card-content updateMemo" data-url="<%= memo_path(memo.id) %>">
      <div class="content">
        <textarea id='<%= @guid %>' name="memo[body]" class="textarea"><%= memo.body %></textarea>
        <% if memo.attachment != nil && memo.attachment != 0 %>
          <img
            src="data:image/png;base64,<%= memo.attachment %>"
            style="width:200px"
            onclick="openModal();"
          />
        <% end %>
      </div>
    </div>
    <footer class="card-footer">
      <div class="card-footer-item" style="width: 100%">
        <div
          class="is-flex is-justify-content-space-between is-align-items-center" style="width: 100%;">
          <%= button_to memo_path(memo), :action => "destroy", :method => :delete, :class => "button is-danger destroyMemo", data: { turbo_confirm: "Are you sure you want to delete?" } do %>
            <i class="fa-regular fa-trash-can fa-fw fa-2x"></i>
          <% end %>
          <button
            class="button cancelEdit"
            style="background-color:var(--ctp-frappe-maroon);color:black;"
          >
            <i class="fa-solid fa-ban fa-fw fa-2x"></i>
          </button>
          <div>
            <!--<%= button_tag type: 'button', class: "button editTags", style: "background-color: var(--ctp-frappe-mauve); color: black;", onclick: "addTag(this);", data: { tags: memo.get_tags} do %>
              <i class="fa-solid fa-hashtag fa-fw fa-2x" aria-hidden="true"></i>
            <% end %>-->
            <button
              class="button saveMemo"
              style="background-color:var(--ctp-frappe-blue);color:black;"
              hx-put="<%= memo_path(memo.id) %>"
            >
              <i class="fa-regular fa-floppy-disk fa-fw fa-2x"></i>
            </button>
          </div>
          <button
            class="editMemo button"
            style="background-color:var(--ctp-frappe-peach);color:black;"
          ><i class="fa-regular fa-pen-to-square fa-fw fa-2x"></i></button>
        </div>
      </div>
    </footer>
  </div>
</div>

app/views/layouts/_new.html.erb
<%= form_for :memo, :url => url_for(:controller => "memos", :action => "create"), html: { class: "memo_form" } do |form| %>
  <div class="card">
    <div class="card-content">
      <div class="content">
        <div class="field">
          <%= form.text_area :body, placeholder: "Memo", class: "textarea" %>
        </div>
      </div>
    </div>
    <footer class="card-footer">
      <div class="card-footer-item">
        <div class="file" style="margin-bottom: 0">
          <label class="file-label">
            <%= form.file_field :attachment,
                            accept: "image/png,image/jpg,image/jpeg",
                            class: "file-input" %>
            <span
              class="file-cta"
              style="background-color: var(--ctp-frappe-green); display: inline-block; margin: 0.25em; border: 1px solid silver; border-radius: 0.25em; padding: .25em 0.5em"
            >
              <i class="fa-solid fa-upload fa-fw fa-2x" style="color: black"></i>
            </span>
          </label>
        </div>
        <div class="right">
          <!--<%= button_tag type: 'button', class: "button", style: "background-color: var(--ctp-frappe-mauve); color: black;", onclick: "addTag();" do %>
            <i class="fa-solid fa-hashtag fa-fw fa-2x" aria-hidden="true"></i>
          <% end %>-->
          <%= button_tag type: 'submit', class: "button is-save" do %>
            <i class="fa-solid fa-floppy-disk fa-fw fa-2x" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    </footer>
  </div>
  <div id="addTagModal" class="modal">
    <div class="modal-background"></div>
    <div class="modal-content">
      <div class="box">
        <article class="media">
          <%= form.text_field :tagName, placeholder: "Tags", class: "input" %>
          <button class="button" style="margin:auto">
            <i class="fa-solid fa-floppy-disk" aria-hidden="true"></i>
          </button>
        </article>
      </div>
    </div>
    <button class="modal-close is-large" aria-label="close"></button>
  </div>
  <script>
    function addTag(elem) {
      $("#addTagModal").find("#memo_tagName").val($(elem).attr("data-tags"));
      $("#addTagModal").addClass("is-active");
    }
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="has-navbar-fixed-top">
  <head>
    <title><%= content_for(:title) || "Memos" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-calendar@7.1.1/dist/css/bulma-calendar.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favicon.png' %>
    <script src="https://cdn.jsdelivr.net/npm/bulma-calendar@7.1.1/dist/js/bulma-calendar.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if notice %>
    <div id="notice" class="notification is-warning"> 
      <p class="notice"><%= notice %></p>
    </div>
    <script>
      (function() {
        setTimeout(hide,1000);
      })();
      function hide() {
        document.getElementById('notice').style.display='none';
      }
    </script>
    <% end %>
    <% if alert %>
    <div class="notification is-danger">
      <button class="delete" onclick="this.parentElement.style.display='none'" ></button>
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
    <div class="container disable-scrollbars" style="overflow-y: scroll; height: 100%">
      <%= yield %>
      <%= render "layouts/dialog" %>
    </div>
  </body>
</html>

app/views/layouts/tags/_listing.html.erb
<div>
  <ul>
    <% for tag in @tags %>
      <li><%= link_to "#" + tag.name, root_path(tid: tag.id) %></li>
    <% end %>
  </ul>
</div>

app/views/memos/index.html.erb
<% if user_signed_in? %>
  <%= csrf_meta_tag %>
  <script>
        function openModal() {
            document.getElementById("modal1")
                .classList.add("is-active");
        }
  </script>
  <div class="columns">
    <div class="column is-four-fifths">
      <div class="memoIndex">
        <%= render "layouts/new" %>
        <% @memos.each do |memo| %>
          <%= render partial: "layouts/memo", object: memo %>
        <% end %>
      </div>
    </div>
    <div class="column">
      <input type="date" data-display-mode="inline" id="memoDate" value="<%= params[:date] %>" />
      <%= tag_cloud %>
    </div>
  </div>
  <script>
    bulmaCalendar.attach('[type="date"]');
    var element = document.querySelector('#memoDate');
    if (element) {
      element.bulmaCalendar.on('select', function(datepicker) {
        console.log(datepicker.data.value());
        var url = "<%= root_path %>?date=" + datepicker.data.value()
        window.location.href = url;
      });
    }

    $(".datetimepicker-footer-clear").on( "click", function() {
        var url = "<%= root_path %>"
        window.location.href = url;
    });

    document.body.addEventListener('htmx:configRequest', function(evt) {
      event.detail.headers['X-CSRF-Token'] = $('meta[name="csrf-token"]').attr('content');
    })

    document.body.addEventListener('htmx:afterSettle', function(evt) {
      setupClicks();
    })

    document.querySelectorAll('.modal-background, .modal-close,.modal-card-head .delete, .modal-card-foot .button').forEach(($el) => {const $modal = $el.closest('.modal');$el.addEventListener('click', () => {$modal.classList.remove("is-active");});});

    function setupClicks() {
  $(".editMemo").on("click", function() {
    $(this).parent().find(".destroyMemo").hide();
    $(this).parent().find(".saveMemo").show();
    $(this).parent().find(".editTags").show();
    $(this).parent().find(".cancelEdit").show();
    var card = $(this).parents(".card");
    card.children(".viewMemo").hide();
    card.children(".updateMemo").show();
    $(this).hide();
  });
  $(".cancelEdit").on("click", function() {
    $(this).parent().find(".destroyMemo").show();
    $(this).parent().find(".saveMemo").hide();
    $(this).parent().find(".editTags").hide();
    $(this).parent().find(".cancelEdit").hide();
    $(this).parents().find(".editMemo").show();
    var card = $(this).parents(".card");
    card.children(".viewMemo").show();
    card.children(".updateMemo").hide();
    $(this).hide();
  });
  $(".saveMemo").on("clickt", function() {
    var card = $(this).parents(".card");
    var url = card.children(".updateMemo").data('url');
    var body = card.find("#editMemoTA").val();
    $.ajax({
      url: url,
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      data: "memo%5Bbody%5D="+encodeURIComponent(body),
      dataType: "html",
      type: 'PUT',
      success: function(result) {
        var memoDiv = card.parents("#memo");
        memoDiv.replaceWith(result);
        setupClicks();
      }
    });
  });
    }
  setupClicks();
  </script>
<% end %>

app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= form_with model: @memo do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memos/search.html.erb
<% if user_signed_in? %>
  <%= csrf_meta_tag %>
  <script>
        function openModal() {
            document.getElementById("modal1")
                .classList.add("is-active");
        }
  </script>
  <div class="memoIndex">
    <%= render "layouts/new" %>
    <% @memos.each do |memo| %>
      <%= render partial: "layouts/memo", object: memo %>
    <% end %>
  </div>
  <script>
    document.body.addEventListener('htmx:configRequest', function(evt) {
      event.detail.headers['X-CSRF-Token'] = $('meta[name="csrf-token"]').attr('content');
    })

    document.body.addEventListener('htmx:afterSettle', function(evt) {
      setupClicks();
    })

    document.querySelectorAll('.modal-background, .modal-close,.modal-card-head .delete, .modal-card-foot .button').forEach(($el) => {const $modal = $el.closest('.modal');$el.addEventListener('click', () => {$modal.classList.remove("is-active");});});

    function setupClicks() {
  $(".editMemo").on("click", function() {
    $(this).parent().find(".saveMemo").show();
    $(this).parent().find(".cancelEdit").show();
    var card = $(this).parents(".card");
    card.children(".viewMemo").hide();
    card.children(".updateMemo").show();
    $(this).hide();
  });
  $(".cancelEdit").on("click", function() {
    $(this).parent().find(".saveMemo").hide();
    $(this).parents().find(".editMemo").show();
    var card = $(this).parents(".card");
    card.children(".viewMemo").show();
    card.children(".updateMemo").hide();
    $(this).hide();
  });
  $(".saveMemo").on("clickt", function() {
    var card = $(this).parents(".card");
    var url = card.children(".updateMemo").data('url');
    var body = card.find("#editMemoTA").val();
    $.ajax({
      url: url,
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      data: "memo%5Bbody%5D="+encodeURIComponent(body),
      dataType: "html",
      type: 'PUT',
      success: function(result) {
        var memoDiv = card.parents("#memo");
        memoDiv.replaceWith(result);
        setupClicks();
      }
    });
  });
    }
  setupClicks();
  </script>
<% end %>

app/views/memos/show.html.erb
<% markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true) %>
<div class="card">
    <header class="card-header">
        <p class="card-header-title"><%= @memo.title %></p>
    </header>
    <div class="card-content">
        <div class="content">
            <%= raw markdown.render(@memo.body) %>

            <%= button_to "Destroy", memo_path(@memo), data: {
                                                         turbo_method: :delete,
                                                         turbo_confirm: "Are you sure?",
                                                       }, :class => "button is-danger right" %>
        </div>
    </div>
</div>
                                             

app/views/settings/index.html.erb
<h1>Settings</h1>

<ul>
  <% @settings.each do |setting| %>
    <li>
      <%= link_to setting.title, setting %>
    </li>
  <% end %>
</ul>

app/views/tags/_form.html.erb
<%= form_with(model: tag) do |form| %>
  <% if tag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<div id="<%= dom_id tag %>">
  <p>
    <strong>Name:</strong>
    <%= tag.name %>
  </p>

</div>

app/views/tags/edit.html.erb
<% content_for :title, "Editing tag" %>

<h1>Editing tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Show this tag", @tag %> |
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tags" %>

<h1>Tags</h1>

<div id="tags">
  <% @tags.each do |tag| %>
    <%= render tag %>
    <p>
      <%= link_to "Show this tag", tag %>
    </p>
  <% end %>
</div>

<%= link_to "New tag", new_tag_path %>

app/views/tags/new.html.erb
<% content_for :title, "New tag" %>

<h1>New tag</h1>

<%= render "form", tag: @tag %>

<br>

<div>
  <%= link_to "Back to tags", tags_path %>
</div>

app/views/tags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tag %>

<div>
  <%= link_to "Edit this tag", edit_tag_path(@tag) %> |
  <%= link_to "Back to tags", tags_path %>

  <%= button_to "Destroy this tag", @tag, method: :delete %>
</div>